# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: badcf31092e963868761ee5fa2fbed501666c59fecae464216542966bfc2e294327173ac34487013d00dd344d46fbd711fb0985b956ee428d3eceea3e4dc7ee1

test:
  secret_key_base: 64d64344cd0c4849e0783cd524341ac96c9fe8804e2310d189b193e7ba8e40012fb364acc94f7a6a448ee362c477dd2ce1dafcc4e4b8a72945fd9193f2b6d395

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
